services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend
      args:
        VITE_PUBLIC_CDN_URL: ${VITE_PUBLIC_CDN_URL}
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
    environment:
      - VITE_PUBLIC_CDN_URL=${VITE_PUBLIC_CDN_URL}
      - VITE_API_BASE_URL=${VITE_API_BASE_URL}
    ports:
      - "3000:3000"
    networks:
      - dev

  nginx:
    image: nginx:alpine
    depends_on:
      - frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    networks:
      - dev

  # certbot:
  #   image: certbot/certbot
  #   volumes:
  #     - ./certbot/www:/var/www/certbot
  #     - ./certbot/conf:/etc/letsencrypt
  #   command: >
  #     certonly --webroot --webroot-path=/var/www/certbot
  #     --email progof031@gmail.com --agree-tos --no-eff-email --force-renewal
  #     -d altloc.com -d www.altloc.com
  #     -d mydarkhobby.com -d www.mydarkhobby.com
  #   networks:
  #     - dev

networks:
  dev:
    external: true
